# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
              NF_BEFORE_SCRIPT: wget -O test_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-isoforms/wf-isoforms_test_data.tar.gz && tar -xzvf  test_data.tar.gz
              NF_WORKFLOW_OPTS: "--fastq  ERR6053095_chr20.fastq \
                  --ref_genome chr20/hg38_chr20.fa --ref_annotation chr20/gencode.v22.annotation.chr20.gtf \
                  --jaffal_refBase chr20/ --jaffal_genome hg38_chr20 --jaffal_annotation genCode22"
              NF_IGNORE_PROCESSES: preprocess_reads,merge_transcriptomes
              CI_FLAVOUR: "new"

docker-run:

    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    parallel:
        matrix:
            - MATRIX_NAME: [
                "fusions", "differential_expression", "only_differential_expression", "isoforms"
            ]
    rules:
        # NOTE As we're overriding the rules block for the included docker-run
        #   we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
        #   being incorrectly scheduled for "detached merge request pipelines" etc.
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "isoforms"
          variables:
              NF_BEFORE_SCRIPT: wget -O test_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-isoforms/wf-isoforms_test_data.tar.gz && tar -xzvf  test_data.tar.gz
              NF_WORKFLOW_OPTS: "--fastq  ERR6053095_chr20.fastq --transcriptome-source reference-guided \
                  --ref_genome chr20/hg38_chr20.fa --ref_annotation chr20/gencode.v22.annotation.chr20.gtf"
              NF_IGNORE_PROCESSES: preprocess_reads,merge_transcriptomes
        - if: $MATRIX_NAME == "fusions"
          variables:
              NF_BEFORE_SCRIPT: wget -O test_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-isoforms/wf-isoforms_test_data.tar.gz && tar -xzvf  test_data.tar.gz
              NF_WORKFLOW_OPTS: "--fastq  ERR6053095_chr20.fastq --transcriptome-source reference-guided \
                  --ref_genome chr20/hg38_chr20.fa --ref_annotation chr20/gencode.v22.annotation.chr20.gtf \
                  --jaffal_refBase chr20/ --jaffal_genome hg38_chr20 --jaffal_annotation genCode22"
              NF_IGNORE_PROCESSES: preprocess_reads,merge_transcriptomes
        - if: $MATRIX_NAME == "differential_expression"
          variables:
              NF_BEFORE_SCRIPT: wget -O differential_expression.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-isoforms/differential_expression.tar.gz && tar -xzvf differential_expression.tar.gz
              NF_WORKFLOW_OPTS: "--fastq  differential_expression/differential_expression_fastq \
                  --de_analysis \
                  --ref_genome differential_expression/hg38_chr20.fa --transcriptome-source reference-guided \
                --ref_annotation differential_expression/gencode.v22.annotation.chr20.gtf \
                --direct_rna --minimap_index_opts \\-k15"
              NF_IGNORE_PROCESSES: preprocess_reads,merge_transcriptomes
        - if: $MATRIX_NAME == "only_differential_expression"
          variables:
              NF_BEFORE_SCRIPT: wget -O differential_expression.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-isoforms/differential_expression.tar.gz && tar -xzvf differential_expression.tar.gz
              NF_WORKFLOW_OPTS: "--fastq  differential_expression/differential_expression_fastq \
                  --transcriptome-source precomputed \
                  --de_analysis \
                  --ref_genome differential_expression/hg38_chr20.fa \
                --ref_annotation differential_expression/gencode.v22.annotation.chr20.gtf \
                --direct_rna --minimap_index_opts \\-k15 \
                --ref_transcriptome differential_expression/ref_transcriptome.fasta \
                --transcriptome_assembly false"
              NF_IGNORE_PROCESSES: >
                preprocess_reads,merge_transcriptomes,assemble_transcripts,
                build_minimap_index,get_transcriptome,merge_gff_bundles,run_gffcompare,build_minimap_index,split_bam
